; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]

[env:wheel]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino

upload_protocol = espota
upload_port = 192.168.0.178 
; upload_flags = --auth=admin
; board_build.partitions = default_16MB

build_src_filter =
    +<wheel/>

lib_deps =
    madhephaestus/ESP32Encoder
    
; upload_port = COM13
monitor_speed = 115200
; monitor_port = COM13

[env:base]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

build_src_filter =
    +<base/>

lib_deps =
    robtillaart/AS5600

upload_port = COM10
monitor_speed = 115200
board_upload.use_1200bps_touch = yes
board_upload.wait_for_upload_port = yes
board_upload.require_upload_port = yes
; monitor_port = COM6